{% set name = "plenoptic" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/plenoptic-{{ version }}.tar.gz
  sha256: 74a8ba02854f967e9c9c8af97bb219ab90f61028aefda1cec34c4c0230bfcca6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.1
    - pytorch >=1.8,!=1.12.0
    - pyrtools >=1.0.1
    - scipy >=1.0
    - matplotlib-base >=3.3
    - tqdm >=4.29
    - imageio >=2.5
    - scikit-image >=0.15.0
    - einops >=0.3.0
    - Deprecated
    - importlib-resources >=6.0

test:
  imports:
    - plenoptic
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Python library for model-based stimulus synthesis.
  home: https://github.com/LabForComputationalVision/plenoptic
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - billbrod
