{% set name = "plenoptic" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/plenoptic-{{ version }}.tar.gz
  sha256: d11c9b60d4650e75b5654f06e87fc245efb6291779067ec891287898f7f2ce77

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >=3.7
    - numpy >=1.1
    - pytorch >=1.8,!=1.12.0
    - pyrtools >=1.0.1
    - scipy >=1.0
    - matplotlib-base >=3.3
    - tqdm >=4.29
    - imageio >=2.5
    - scikit-image >=0.15.0
    - einops >=0.3.0

test:
  imports:
    - plenoptic
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Python library for model-based stimulus synthesis.
  home: https://github.com/LabForComputationalVision/plenoptic
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - billbrod
